#Google Analytics
analytics-id: #leave blank to not use Analytics

#Subtitle
subtitle:
  active: true
  text: Crow's Nest

#Nav 
nav:
  pages:
    active: true
  social:
    active: true
    
#Posts
posts: 
active: false

#Featured images in homepage
featured-img:
  active: false

#Show categories at the end of posts
categories:
  active: false

#Show date and read time under the post title
date-under-post:
  active: false

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: false
  title: "You May Also Enjoy"

#Comments
comments: false
